version: '4.0'
services:
  postgres:
    image: postgres:14-alpine
    networks:
      - arch-network
    container_name: postgres
    ports: 
      - 5432:5432
    expose:
      - 8100
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - TZ=${TZ:-Europe/Luxembourg}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8820:80"
    networks:
      - arch-network
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-postgres@postgres.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - './data:/usr/src/app/data:delegated'
      - './project:/usr/src/app/project:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000